dist: bionic
language: go

go:
- 1.x

git:
  depth: 2

env:
  global:
  - GO111MODULE=on
  - PATH=bin:$PATH
  - DOCKER_USERNAME=marcomm
  - secure: "m/Kx4rY9E/rEYc9DoZNfZS/SBoY0zgolg/me6BWOv2gmPXdCVeN1EGMAwleE+NO8YNP1w7Ze65XPpPFE9ePuP8Lgwo0ORWFe82V0DNQaAyrpGnXHJ9bv+ftajrjBXVR6tl28apenlJt/IYWsr2ssU9azAn/BcSvb+SY4FAilf1+ijMHiXPes2c4tvx3m/pmro8ARBsYR7mzmIgWFgVeDpVZBn1rJr8/Arc/0MP15QwBbnZlhviE+9/D7fiJTjIFlC54b5VnLT7IzzoYTWEe0qmYr1UTCxBoaVbXl4htvuG53FcBEDEFiKdSnVRFuyKmIN9PC0rqzO+9Eu5j4TOkr1mOaaS6JmBECrKf/FuG82job5eRzIrygBB9EH+tyZ9+yxeF6NURt3vww/HhKPuBmCg/SVGQUIv/u7VN3THp6sOqEUPN1v/FhYbliS4Nu83zpqlSEQACCqa00L8OREFK4ca35fRNBTEMd9CJE/EMcOiHbGqh7YdW0hXgcrXz1B4g2++/T4SomDyoKJ2i400kiZYpiyndIPDdilIMcP/bOVjwvk554TT7SGwK1PQ73FOEQPnxwOf23AuTsRvBDlNnUpQ8ARlLXT9Kkd4urAqVALObycsz8BjYRHkVhWVfrdByl1uGC74rT6IMcQUwZShjB22aenvZyohZY1i/amAwvuLk="

services:
- docker

install:
- curl --silent --location https://taskfile.dev/install.sh | sh
- which task
- task --version

script:
# This is to fail fast, see https://github.com/travis-ci/travis-ci/issues/1066
# :-(
- task test || exit 1
- task docker-build || exit 1
- task docker-smoke || exit 1
- task docker-push || exit 1
