# https://taskfile.dev

version: '2'

env:
  DOCKER_IMAGE: travis-go-dockerhub

tasks:
  build:
    dir: bin
    cmds:
      - go build ../cmd/hello
  docker-build:
    cmds:
      - docker build --tag $DOCKER_IMAGE .
  docker-smoke:
    cmds:
      - docker run --interactive --tty $DOCKER_IMAGE /bin/hello
  docker-login:
    silent: true
    cmds:
      - echo "Logging in to DockerHub"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN 2> /dev/null
  docker-push:
    deps: [docker-login]
    cmds:
      - docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
      - echo Pushing $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG 
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
    vars:
      GIT_BRANCH:
        # On Travis, no matter the git clone depth, we always get a detached HEAD, so we
        # cannot just ask git what is our branch.
        # In addition, the variable TRAVIS_BRANCH changes meaning when the build is a PR:
        # it becomes the name of the merge target branch (so it would become "master").
        # This is why we are forced to all this machinery :-/
        sh: |-
          if [ -z "$TRAVIS" ]; then
              git symbolic-ref --short HEAD
          elif [ -n "$TRAVIS_PULL_REQUEST_BRANCH" ]; then
              echo $TRAVIS_PULL_REQUEST_BRANCH
          else
              echo $TRAVIS_BRANCH
          fi
    env:
      DOCKER_TAG: "{{.GIT_BRANCH}}-latest"
