# https://taskfile.dev

version: '2'

env:
  DOCKER_IMAGE: travis-go-dockerhub

tasks:
  test:
    cmds:
      - go test ./hello
  build:
    dir: bin
    cmds:
      - go build ../cmd/hello
  docker-build:
    cmds:
      - docker build --tag $DOCKER_IMAGE .
  docker-smoke:
    cmds:
      - docker run --rm --interactive --tty $DOCKER_IMAGE /bin/hello
  docker-login:
    silent: true
    cmds:
      - echo "Logging in to DockerHub"
      - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN 2> /dev/null
  docker-push:
    deps: [docker-login]
    cmds:
      - docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
      - echo Pushing $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG 
      - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
      - |-
        if [ -n "$DOCKER_LATEST" ]; then
            docker tag $DOCKER_IMAGE $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_LATEST
            echo Pushing $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_LATEST
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_LATEST
        fi
    env:
      DOCKER_TAG:
        sh: ci/git-ref-to-docker-tag.sh
      DOCKER_LATEST:
        sh: ci/git-latest.sh
